spring.application.name=auth
spring.config.import=optional:file:.env[.properties]

spring.messages.basename=i18n/bussiness,i18n/general,i18n/validation
spring.messages.encoding=UTF-8
spring.web.locale=en
spring.web.locale-resolver=fixed

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.flywaydb=DEBUG



spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.address=${APP_HOST}
server.port=${APP_PORT:5000}

spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.locations=classpath:db/migrations