# Usar la imagen oficial de PostgreSQL
FROM postgres:16

# Variables de entorno para configurar usuario, contraseña y base de datos
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=auth

# Exponer el puerto por defecto
EXPOSE 5432
